.PHONY: clean All

All:
	@echo "----------Building project:[ project3 - Debug ]----------"
	@cd "project3" && "$(MAKE)" -f  "project3.mk"
clean:
	@echo "----------Cleaning project:[ project3 - Debug ]----------"
	@cd "project3" && "$(MAKE)" -f  "project3.mk" clean
