.PHONY: clean All

All:
	@echo "----------Building project:[ project5 - Debug ]----------"
	@cd "project5" && "$(MAKE)" -f  "project5.mk"
clean:
	@echo "----------Cleaning project:[ project5 - Debug ]----------"
	@cd "project5" && "$(MAKE)" -f  "project5.mk" clean
