.PHONY: clean All

All:
	@echo "----------Building project:[ 3 - Debug ]----------"
	@cd "3" && "$(MAKE)" -f  "3.mk"
clean:
	@echo "----------Cleaning project:[ 3 - Debug ]----------"
	@cd "3" && "$(MAKE)" -f  "3.mk" clean
